# GET http://localhost:5000/api/stores

POST http://localhost:5000/api/stores/ HTTP/1.1
content-type: application/json

{
    "name": "woolworths",
    "start_url": "https://www.woolworths.com.au/shop/browse/",
    "single_product_tile": "//wow-tile/div/wow-shelf-product-tile",
    "single_product_name": "shelfProductTile-descriptionLink",
    "single_product_dollar": "price-dollars",
    "single_product_cents": "price-centsPer",
    "bundle_product_tile": "//wow-tile/div/wow-shelf-bundle-tile",
    "bundle_product_title": "shelfBundleTile-title",
    "bundle_product_names": "shelfProductVariant-variant",
    "bundle_product_prices": "shelfProductVariant-price"
}
